# -*- coding: utf-8 -*-
"""メインプログラム

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccjiM0ip7AGdreXVakQeAkAU7JmpeOrn
"""

import os
from flask import Flask, render_template

app = Flask(__name__)

@app.route('/')
def index():
    # 環境変数からAPIキーを取得します
    # ローカルでテストする場合は、ここに直接キーを入れても動きますが、
    # GitHubに上げる際は環境変数 'GEMINI_API_KEY' を設定するのが安全です。
    api_key = os.environ.get("GEMINI_API_KEY", "")

    # HTMLファイル（templates/index.html）を表示し、APIキーを渡します
    return render_template('index.html', api_key=api_key)

if __name__ == '__main__':
    # ポート設定（Renderなどのクラウド環境用）
    port = int(os.environ.get("PORT", 8080))
    app.run(host='0.0.0.0', port=port, debug=True)